config/routes.rb
Rails.application.routes.draw do
  constraints(Subdomain::Admin) do
    devise_for :admins, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    unauthenticated :admin do
      devise_scope :admin do
        root to: "active_admin/devise/sessions#new"
      end
    end

    authenticated :admin do
      root to: "admin/dashboard#index"
    end
  end

  devise_for :users, controllers: { sessions: "users/sessions" }

  constraints(Subdomain::Dashboard) do
    namespace :profiles do
      resources :build
    end

    resources :profiles, only: [:show, :update]

    namespace :requisitions do
      resources :sponsorships, except: [:index] do
        collection do
          get "list_schools"
          get "school/:school_id" => "sponsorships#school"
        end
      end
      resources :audits, except: [:index, :show, :destroy] do
        resources :reports
      end
      resources :offers, only: [:create, :destroy]
    end

    resources :reviews

    resources :invoices, only: [:index] do
      collection do
        put "pay_invoices"
      end
    end

    resources :requisitions, only: [:index, :show] do
      member do
        get "progress"
      end
      collection do
        get "search"
      end
    end


    resources :wallets, only: [:show, :create]

    resources :dashboard, only: [:index] do
      collection do
        put "upload_report" => "dashboard#upload_report", as: :upload_pdf_report
      end
    end
    root 'dashboard#index', as: :user_authenticated_root
  end


  root to: 'visitors#welcome'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :render_authenticated_area!

  before_action :generate_client_token, if: Proc.new { |controller| controller.current_user.has_role?(Sponsor) }

  layout "dashboard"

  def index
    action = current_user.active_participant.pluralize
    send(action)
    render action: action.to_sym
  end

  def students
    @sponsorship_requisition = current_student.sponsorship_requisitions
                                        .includes(:school, :audit_offers, :audit_requisition)
                                        .unrejected_requisitions.first

    @rejected_requisitions   = current_student.sponsorship_requisitions.includes(:school, :audit_offers, :audit_requisition => :audit_report).rejected_requisitions
  end

  def sponsors
    @sponsorship_requisitions = current_sponsor.sponsorship_requisitions.includes(:school, :audit_offers, :audit_requisition).order("created_at desc").limit(4)
  end

  def auditors
    @audit_requisition = auditor_on_going_progress
    if @audit_requisition
      set_geocode_location!(@audit_requisition.school.address)
      @audit_report = @audit_requisition.audit_report
    end
    @completed_cases = current_auditor.audit_requisitions.completed_requisitions.includes(:sponsorship_requisition)
  end

  def upload_report
    sleep 6
    Requisition.transaction do
      @audit_requisition = auditor_on_going_progress

      respond_to do |format|
        if @audit_requisition.update_attributes(report_uploaded_at: DateTime.now, status: Requisition::AUDIT_STATUS[:completed])
          @audit_requisition.sponsorship_requisition.generate_results
          flash[:notice] = "Requisition has been successfully completed."
          # NotificationsMailer.report_uploaded(@audit_requisition.sponsorship_requisition.provider.user).deliver
          # NotificationsMailer.results(@audit_requisition.sponsorship_requisition.owner.user).deliver
          format.json { render json: { status: 200, redirect: root_path } }
        else
          format.json { render json: { status: 500 } }
        end
      end
    end
  end

  def auditor_on_going_progress
    current_auditor.audit_requisitions.approved_requisitions.first
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def render_progress(progress_owner, options = {}, &block)
    options["#{progress_owner.downcase}_content".to_sym] = block
    render partial: "requisitions/progress/requisition_status", locals: options
  end

  def rating_input(rating)
    %Q{<input class="review-rating rating rating-loading" value="#{rating}" data-display-only='true' data-show-clear="false" data-show-caption="true">}.html_safe
  end

  def rating_status(rating)
    if rating < 2.5
      "label-danger"
    elsif rating == 2.5
      "label-info"
    else
      "label-success"
    end
  end

  # TODO Set Dynamic Content for partials that can help in defining positions based on user type in partials
  # def render_content(content_title)
  #   inner = -> () {
  #     content_title
  #   }
  #   inner.call()
  # end
  #
  # InitiateDynamicPosition = Struct.new (
  #   :partial
  # ) do
  #   def self.set_position(pos)
  #     capture(&)
  #   end
  # end
end

app/views/dashboard/auditors.html.haml
.dashboard
  #auditors
    .row
      .col-md-3.pull-right
        %blockquote.blockquote-reverse
          .wallet_funds
            %strong My Wallet
            %small.funds
              = number_to_currency(current_auditor.funds)
      .col-md-9
        %h1.page-header.label-name
          %i.fa.fa-tachometer
          Dashboard
        %h1.user-name
          %small= current_user.full_name
        %p
          &ndash;
          %em "Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut "
    .stats
      .container-fuild
        .row
          .col-md-6
          .col-md-5.pull-right
            .right-section
              .panel.panel-success
                .panel-heading
                  .panel-title
                    %strong= current_auditor.audit_requisitions.completed_case.length
                    %span Completed
    - if @audit_requisition.present?
      .bs-callout.bs-callout-info
        %h4
          %strong On Going Case
      .applied-requisitions
        .requisition-section
          = render_progress "Auditor", requisition: @audit_requisition do
            .audit-report-actions
              = render partial: "requisitions/progress/auditors/upload_report_form"
              %p
                %strong Note:
                If you are not able to upload Report withen 3 weeks your requisition will be cancelled automatically.
    - else
      .bs-callout.bs-callout-success.text-center
        %h3
          %strong There is no Requisition Progress
        Search
        = link_to "New Requisitions", search_requisitions_path
        of amazing Sponsorship Programs.
    .bs-callout.bs-callout-success
      %h4
        %strong Completed Cases

    - if @completed_cases.present?
      - @completed_cases.each do |requisition|
        .applied-requisitions
          .requisition-section
            = render_progress "Auditor", requisition: requisition.sponsorship_requisition, school_view: false, content: false do
              %table.table.table-bordered#overall_summary
                %tbody
                  %tr
                    %th.text-center
                      Rated
                    %th.text-center
                      Reviews
                    %th.text-center
                      Report
                  %tr
                    %td
                      = 3
                    %td
                      Lorem ipsum dolor sit amet, consectetur adipisicing elit
                    %td
                      = link_to requisitions_audit_report_path(requisition, requisition.audit_report, deposition: "attachment", format: :pdf), class: "btn btn-warning btn-block btn-sm" do
                        %i.fa.fa-file-text
                        Download Report
    - else
      .container-fluid
        .bs-callout.bs-callout-primary
          No Completed Cases

app/views/dashboard/sponsors.html.haml
- content_for :javascript do
  Sponsors.initializePayments();
  Landing.initializeFundingChart()

.dashboard
  #sponsors
    .row
      .col-md-6
        %blockquote.blockquote.funds-blockquote
          Welcome
          %small= current_user.full_name
      .col-md-6
        %blockquote.blockquote.blockquote-reverse.funds-blockquote
          Total Funds in your Wallet
          %small= number_to_currency(current_sponsor.funds)
          = link_to "#", :type => "button", id: "sponsorWalletModalLink" do
            %i.fa.fa-plus
            Add Funds to my Wallet

    .stats
      .container-fuild
        .row
          .col-md-6
            #fundingChartContainer{style: "height:300px;"}
          .col-md-5.pull-right
            .right-section
              .panel.panel-danger
                .panel-heading
                  .panel-title
                    %strong= @sponsorship_requisitions.completed_case.length
                    %span All Cases

              .panel.panel-success
                .panel-heading
                  .panel-title
                    %strong= @sponsorship_requisitions.on_going_case.length
                    %span On Going Cases
    .bs-callout.bs-callout-info
      %h4
        %strong Recent Cases
    - if @sponsorship_requisitions.present?
      - @sponsorship_requisitions.each do |sponsorship_requisition|
        .bs-callout.bs-callout-primary
          .requisition-details
            .container-fluid
              .row
                .col-md-2
                  = image_tag requisition_progress_icons[sponsorship_requisition.status], class: "img-responsive"
                .col-md-10
                  %blockquote.blockquote
                    %h2.page-header
                      = sponsorship_requisition.subject
                      %small
                        Created On -
                        = sponsorship_requisition.created_at.strftime("%d %B, %Y")
                  %p
                    = simple_format sponsorship_requisition.description
                  %ul.list-inline
                    %li
                      %label Grade Level
                      %br
                      %span= sponsorship_requisition.grade_level
                    %li
                      %label School
                      %br
                      %span= sponsorship_requisition.school.name
                    %li
                      %label Tenure
                      %br
                      %span
                        = sponsorship_requisition.tenure
                        Month(s)
                    %li
                      %label Status
                      %br
                      %span.label{class: "label-#{requisition_progress_classes[sponsorship_requisition.status]}"}
                        = sponsorship_requisition.status.humanize
                    - if sponsorship_requisition.audit_requisition.present? and sponsorship_requisition.audit_requisition.open?
                      %li
                        %label Audit Offers
                        %br
                        %span
                          = "(#{sponsorship_requisition.audit_requisition.audit_offers.length})"
                    - elsif sponsorship_requisition.audit_requisition.present? and sponsorship_requisition.audit_requisition.provider.present?
                      %li
                        %label Auditor
                        %br
                        %span
                          = link_to sponsorship_requisition.audit_requisition.provider.user.full_name, profile_path(sponsorship_requisition.audit_requisition.provider.user_id)

                  %hr
                  = link_to  progress_requisition_path(sponsorship_requisition.id), class: "btn btn-info btn-block-container" do
                    View Status
    - else
      .container-fluid
        .bs-callout.bs-callout-danger
          No recent Case

.modal-popup{data: { valid: popup_is_set?.to_s }}
  - allow_popup(false)
  = render partial: "dashboard/sponsors/wallet"

app/views/dashboard/students.html.haml
.dashboard
  #students
    .authform-container-fluid
      .row
        .col-md-3.pull-right
          %a.thumbnail{href: "#"}
            = image_tag current_user.avatar.url(:medium), class: 'img-responsive'
        .col-md-9
          %h1.page-header.label-name
            %i.fa.fa-tachometer
            My Dashboard
          %h1.user-name
            %small= current_user.full_name
            %span= "(#{current_student.age} year(s) old)"

  - if @sponsorship_requisition.blank?
    .bs-callout.bs-callout-info.text-center
      %h3
        %strong There is no Requisition In Progress
      Create your
      = link_to "New Requisition", new_requisitions_sponsorship_path
      to get Sponsorship Offers.
  - else
    .student-dashboard

      .bs-callout.bs-callout-info
        %h4
          %strong On Going Case
      .bs-callout.bs-callout-primary
        .requisition-details
          = render partial: "dashboard/students/requisition", locals: { sponsorship_requisition: @sponsorship_requisition }

      .bs-callout{class: "bs-callout-warning"}
        %h4
          %strong
          My Sponsor

      .container-fluid
        .bs-callout.bs-callout-primary
          - if @sponsorship_requisition.try(:provider).present?
            = render partial: "requisitions/shared/approved_provider_details", locals: { provider: @sponsorship_requisition.provider }
          - else
            No Sponsorship Offers for your requisition

      .bs-callout{class: "bs-callout-success"}
        %h4
          %strong
          My Auditor

      .container-fluid
        .bs-callout.bs-callout-primary
          - if @sponsorship_requisition.audit_requisition.try(:provider).present?
            = render partial: "requisitions/shared/approved_provider_details", locals: { provider: @sponsorship_requisition.audit_requisition.provider }
          - else
            No Audit Offers for your requisition

  .bs-callout{class: "bs-callout-danger"}
    %h4
      %strong
      Rejected Requisitions

  - if @rejected_requisitions.present?
    .requisition-details
      = render partial: "dashboard/students/requisition", collection: @rejected_requisitions, as: :sponsorship_requisition
  - else
    .container-fluid
      .bs-callout.bs-callout-primary
        No Rejected Requisitions