config/routes.rb
Rails.application.routes.draw do
  constraints(Subdomain::Admin) do
    devise_for :admins, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    unauthenticated :admin do
      devise_scope :admin do
        root to: "active_admin/devise/sessions#new"
      end
    end

    authenticated :admin do
      root to: "admin/dashboard#index"
    end
  end

  devise_for :users, controllers: { sessions: "users/sessions" }

  constraints(Subdomain::Dashboard) do
    namespace :profiles do
      resources :build
    end

    resources :profiles, only: [:show, :update]

    namespace :requisitions do
      resources :sponsorships, except: [:index] do
        collection do
          get "list_schools"
          get "school/:school_id" => "sponsorships#school"
        end
      end
      resources :audits, except: [:index, :show, :destroy] do
        resources :reports
      end
      resources :offers, only: [:create, :destroy]
    end

    resources :reviews

    resources :invoices, only: [:index] do
      collection do
        put "pay_invoices"
      end
    end

    resources :requisitions, only: [:index, :show] do
      member do
        get "progress"
      end
      collection do
        get "search"
      end
    end


    resources :wallets, only: [:show, :create]

    resources :dashboard, only: [:index] do
      collection do
        put "upload_report" => "dashboard#upload_report", as: :upload_pdf_report
      end
    end
    root 'dashboard#index', as: :user_authenticated_root
  end


  root to: 'visitors#welcome'
end

app/models/invoice.rb
# == Schema Information
#
# Table name: invoices
#
#  id             :integer          not null, primary key
#  issued_at      :datetime
#  requisition_id :integer
#  invoice_amount :float
#  status         :integer          default("open")
#  invoice_number :string
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  month          :integer
#  year           :integer
#

class Invoice < ApplicationRecord
  belongs_to :requisition
  validates_uniqueness_of :invoice_number

  # default_scope { order("year asc") }

  enum status: { open: 0, paid: 1 }

  scope :unpaid, -> { where("invoices.status = 0") }
  scope :current_month, -> { where("month = ? and year = ?", Date.today.month, Date.today.year) }

  before_create do
    generate_invoice_number
  end

  before_destroy do
    revert_reserved_funds
  end

  def self.generate(requisition)
    ActiveRecord::Base.transaction do
      total = []
      s_date = requisition.start_date
      e_date = requisition.end_date

      (s_date...e_date).select {|d| d.day == 1}.map do |date|
        attrs = {
          issued_at: DateTime.now,
          requisition_id: requisition.id,
          month: date.month,
          year: date.year,
          invoice_amount: requisition.school.fees
        }
        total << attrs[:invoice_amount]
        create(attrs)
      end

      requisition.update_attribute(:reserved_funds, total.sum)
    end
  end

  def self.due_amount
    unpaid.sum(&:invoice_amount)
  end

  def self.total_paid_invoices
    paid.sum(&:invoice_amount)
  end

  def self.total_current_invoices
    current_month.sum(&:invoice_amount)
  end

  def self.due_invoices
    unpaid.select{|i| Date.new(i.year, i.month, 1) <= Date.today}
  end

  def self.future_invoices
    unpaid.select{|i| Date.new(i.year, i.month, 1) > Date.today}
  end

  def self.due_current_month_invoices
    unpaid.select{|i| i.month + 1 == Date.today.month + 1 and i.year == Date.today.year}
  end

  def of_current_month?
    month == Date.today.month and year == Date.today.year
  end

  def pay
    status = false
    begin
      transaction do
        school = requisition.school
        school.update_attribute(:funds, school.funds + invoice_amount)

        sponsor = requisition.provider
        sponsor.update_attribute(:funds, sponsor.funds - invoice_amount)

        requisition.update_attribute(:reserved_funds, requisition.reserved_funds - invoice_amount)

        update_attribute(:status, 1)
        status = true
      end
    rescue => e
      Rails.logger.info "Exception Raised #{e.message}"
      status = false
    end

    status
  end

  def revert_reserved_funds
    if open?
      requisition.update_attribute(:reserved_funds, requisition.reserved_funds - invoice_amount) if requisition.reserved_funds >= invoice_amount
    end
  end

  def generate_invoice_number
    self.invoice_number = "#%04i" % (((self.class.last.try(:invoice_number).split("#").last rescue nil) || 0).to_i + 1).to_s
  end

  def month_humanize
    Date.new(year, month, 1).strftime("%b")
  end
end

app/models/sponsor.rb
# == Schema Information
#
# Table name: sponsors
#
#  id                    :integer          not null, primary key
#  user_id               :integer
#  created_at            :datetime         not null
#  updated_at            :datetime         not null
#  volunteer             :boolean          default(FALSE)
#  organization_title    :string
#  organization          :boolean          default(FALSE)
#  braintree_customer_id :string
#  funds                 :float
#

class Sponsor < ApplicationRecord
  include CommonUser
  include StepValidator
  has_many :audit_requisitions, class_name: "Requisition", as: :owner, :dependent => :destroy # Sponsor created requisitions
  has_many :sponsorship_requisitions, class_name: "Requisition", as: :provider # Sponsor offered requisitions

  has_many :invoices, through: :sponsorship_requisitions

  has_many :reviews, as: :ratee

  delegate :received_reviews, :given_reviews, to: :user

  has_many :offers, as: :creator, :dependent => :destroy

  with_options if: -> { business_user? } do |validate|
    validate.validates_presence_of :organization_title
  end

  def business_user?
    organization == true
  end

  def has_payment_info?
    braintree_customer_id
  end

  def empty_wallet?
    funds <= 0
  end

  def find_or_make_customer(params)
    success = false
    if !has_payment_info?
      result = Braintree::Customer.create(
          :first_name => self.user.first_name,
          :last_name => self.user.last_name,
          :email => self.user.email,
          :payment_method_nonce => params[:payment_method_nonce],
          :credit_card => {
              :options => {
                  :make_default => true
              }
          }
      )
      if result.success?
        success = true
        self.braintree_customer_id = result.customer.id
      end
    else
      success = true
    end

    success
  end

  def funds
    read_attribute(:funds) || 0
  end

  def Hello
    self.includes(:user)
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  before_action :set_invoices, only: [:pay_invoices]
  before_action :authorise_student, :authorise_auditor, :authorise_auditor

  def index
    @scope = params[:scope] || "paid"
    @invoices = current_sponsor.invoices.send(@scope == "open" ? "unpaid" : @scope)

    if params[:due].present?
      @due_invoices = true
      @invoices = @invoices.due_current_month_invoices
    elsif params[:due].blank? and params[:due] == false
      @due_invoices = false
      @invoices = @invoices.future_invoices
    end
  end

  def pay_invoices
    failed = @invoices.map(&:pay).uniq.include?(false)
    redirect_to progress_requisition_path(@invoices.first.requisition_id)
    if failed.present?
      flash[:alert] = "There was a problem while Paying Invoice"
    else
      months = []
      @invoices.each do |invoice|
        months << invoice.month_humanize
      end
      flash[:notice] = "Invoices Paid for the month of #{months.join(', ')}"
    end
  end

  def set_invoices
    @invoices = Invoice.where(id: params[:invoice_ids])
  end
end

app/views/invoices/_invoices.html.haml
- content_for :javascript do
  Invoice.submitInvoice()

- if invoices.present?
  = form_tag pay_invoices_invoices_path, method: :put do
    %table.table.table-bordered#invoices
      %thead
        %tr
          %th.text-center
          %th.text-center
            Invoice Number
          %th.text-center
            Invoice Amount
          %th.text-center
            Status
          %th.text-center
            Month
          %th.text-center
            Year

      %tbody
        - invoices.order("year asc").each do |invoice|
          %tr
            %td.text-center
              - if invoice.open? and invoice.of_current_month? && !defined?(hide_form)
                .checkbox
                  = check_box_tag "invoice_ids[]", invoice.id, false, id: "pay_invoice_#{invoice.id}"
                  %label{:for => "pay_invoice_#{invoice.id}"}
                    -
            %td.text-center
              = invoice.invoice_number
            %td.text-center
              - if invoice.paid?
                %s= number_to_currency(invoice.invoice_amount)
              - else
                = number_to_currency(invoice.invoice_amount)
            %td.text-center
              %span.label{class: "label-#{invoice_status[invoice.status]}"}= invoice.status.humanize
            %td.text-center
              = invoice.month_humanize
            %td.text-center
              = invoice.year
        - if invoices.present?
          %tr
            %th.text-center Total
            %th
            %td.text-center
              - if defined?(paid_invoices)
                = number_to_currency(invoices.total_paid_invoices)
              - elsif defined?(current_invoices)
                = number_to_currency(invoices.total_current_invoices)
              - else
                = number_to_currency(invoices.due_amount)
            %td
            %td.text-center= pluralize(invoices.length, "month")
            %td

    - unless defined?(hide_form)
      - if invoices.present? and invoices.due_invoices.any?
        = submit_tag "Pay Now", class: "btn btn-block-container btn-success", id: "pay-invoice-submit"
      - else
        There are no current month invoice in pending
- else
  No Invoice Present

app/views/invoices/index.html.haml
- content_for :javascript do
  Settings.initializeDataTables("table#invoices");
%h1.text-center.page-header
  Invoices

.row
  .col-md-3
    %ul.nav.nav-pills.nav-stacked{:role => "tablist"}
      %li{class: @scope == "paid" ? "active" : ""}
        = link_to "Paid Invoices", invoices_path(scope: "paid")
      %li{class: @scope == "open" && @due_invoices.present? ? "active" : ""}
        = link_to "Current Invoices", invoices_path(scope: "open", due: true)
      %li{class: @scope == "open" && @due_invoices.blank? ? "active" : ""}
        = link_to "Future Invoices", invoices_path(scope: "open")

  .col-md-9
    .tab-content
      - if @scope == "paid"
        #paid.tab-pane.active{:role => "tabpanel"}
          .bs-callout.bs-callout-info
            %h3 All Paid Invoices
          = render partial: "invoices/invoices", locals: { invoices: @invoices, hide_form: true, paid_invoices: true }
      - if @scope == "open" and @due_invoices.present?
        #current.tab-pane.active{:role => "tabpanel"}
          .bs-callout.bs-callout-info
            %h3
              Invoices for the month of
              %strong= Date.today.strftime "%b"
          = render partial: "invoices/invoices", locals: { invoices: @invoices, current_invoices: true }
      - if @scope == "open" and @due_invoices.blank?
        #future.tab-pane.active{:role => "tabpanel"}
          .bs-callout.bs-callout-info
            %h3
              Future Invoices
          = render partial: "invoices/invoices", locals: { invoices: @invoices, hide_form: true }