config/routes.rb
Rails.application.routes.draw do
  constraints(Subdomain::Admin) do
    devise_for :admins, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    unauthenticated :admin do
      devise_scope :admin do
        root to: "active_admin/devise/sessions#new"
      end
    end

    authenticated :admin do
      root to: "admin/dashboard#index"
    end
  end

  devise_for :users, controllers: { sessions: "users/sessions" }

  constraints(Subdomain::Dashboard) do
    namespace :profiles do
      resources :build
    end

    resources :profiles, only: [:show, :update]

    namespace :requisitions do
      resources :sponsorships, except: [:index] do
        collection do
          get "list_schools"
          get "school/:school_id" => "sponsorships#school"
        end
      end
      resources :audits, except: [:index, :show, :destroy] do
        resources :reports
      end
      resources :offers, only: [:create, :destroy]
    end

    resources :reviews

    resources :invoices, only: [:index] do
      collection do
        put "pay_invoices"
      end
    end

    resources :requisitions, only: [:index, :show] do
      member do
        get "progress"
      end
      collection do
        get "search"
      end
    end


    resources :wallets, only: [:show, :create]

    resources :dashboard, only: [:index] do
      collection do
        put "upload_report" => "dashboard#upload_report", as: :upload_pdf_report
      end
    end
    root 'dashboard#index', as: :user_authenticated_root
  end


  root to: 'visitors#welcome'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :render_authenticated_area!

  before_action :generate_client_token, if: Proc.new { |controller| controller.current_user.has_role?(Sponsor) }

  layout "dashboard"

  def index
    action = current_user.active_participant.pluralize
    send(action)
    render action: action.to_sym
  end

  def students
    @sponsorship_requisition = current_student.sponsorship_requisitions
                                        .includes(:school, :audit_offers, :audit_requisition)
                                        .unrejected_requisitions.first

    @rejected_requisitions   = current_student.sponsorship_requisitions.includes(:school, :audit_offers, :audit_requisition => :audit_report).rejected_requisitions
  end

  def sponsors
    @sponsorship_requisitions = current_sponsor.sponsorship_requisitions.includes(:school, :audit_offers, :audit_requisition).order("created_at desc").limit(4)
  end

  def auditors
    @audit_requisition = auditor_on_going_progress
    if @audit_requisition
      set_geocode_location!(@audit_requisition.school.address)
      @audit_report = @audit_requisition.audit_report
    end
    @completed_cases = current_auditor.audit_requisitions.completed_requisitions.includes(:sponsorship_requisition)
  end

  def upload_report
    sleep 6
    Requisition.transaction do
      @audit_requisition = auditor_on_going_progress

      respond_to do |format|
        if @audit_requisition.update_attributes(report_uploaded_at: DateTime.now, status: Requisition::AUDIT_STATUS[:completed])
          @audit_requisition.sponsorship_requisition.generate_results
          flash[:notice] = "Requisition has been successfully completed."
          # NotificationsMailer.report_uploaded(@audit_requisition.sponsorship_requisition.provider.user).deliver
          # NotificationsMailer.results(@audit_requisition.sponsorship_requisition.owner.user).deliver
          format.json { render json: { status: 200, redirect: root_path } }
        else
          format.json { render json: { status: 500 } }
        end
      end
    end
  end

  def auditor_on_going_progress
    current_auditor.audit_requisitions.approved_requisitions.first
  end
end

app/helpers/dashboard_helper.rb
module DashboardHelper
  def render_progress(progress_owner, options = {}, &block)
    options["#{progress_owner.downcase}_content".to_sym] = block
    render partial: "requisitions/progress/requisition_status", locals: options
  end

  def rating_input(rating)
    %Q{<input class="review-rating rating rating-loading" value="#{rating}" data-display-only='true' data-show-clear="false" data-show-caption="true">}.html_safe
  end

  def rating_status(rating)
    if rating < 2.5
      "label-danger"
    elsif rating == 2.5
      "label-info"
    else
      "label-success"
    end
  end

  # TODO Set Dynamic Content for partials that can help in defining positions based on user type in partials
  # def render_content(content_title)
  #   inner = -> () {
  #     content_title
  #   }
  #   inner.call()
  # end
  #
  # InitiateDynamicPosition = Struct.new (
  #   :partial
  # ) do
  #   def self.set_position(pos)
  #     capture(&)
  #   end
  # end
end

app/views/layouts/dashboard/_head.html.haml.html.haml
%meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
%title= content_for?(:title) ? yield(:title) : 'EVS - Education Voucher Scheme'
%meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Evs'}"}
= stylesheet_link_tag 'dashboard', media: 'all', 'data-turbolinks-track' => 'reload'
= javascript_include_tag 'dashboard', 'data-turbolinks-track' => 'reload'
= csrf_meta_tags
= include_google_map(places: true)
%script{:src => "https://js.braintreegateway.com/js/braintree-2.30.0.min.js"}

app/views/layouts/dashboard/_navigation.html.haml
/ Navigation
%nav.navbar.navbar-default.navbar-fixed-top{:role => "navigation"}
  .container
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => root_path}
        %i.fa.fa-tachometer.fa-2x
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      - unless current_user.incomplete_profile?
        %ul.nav.navbar-nav
          - if current_user.has_role?(Auditor) || current_user.has_role?(Sponsor)
            %li
              = link_to search_requisitions_path do
                %i.fa.fa-search-plus
                Search For Applied Requisitions

          - if current_user.has_role?(Sponsor)
            %li
              = link_to invoices_path do
                %i.fa.fa-list-alt
                Invoices
      %ul.nav.navbar-nav.navbar-right
        - unless current_user.incomplete_profile?
          %li= link_to current_user.username, "#"
          %li= link_to 'Profile', profile_path(current_user.id)
        %li.dropdown
          %a.dropdown-toggle{"aria-expanded" => "false", "aria-haspopup" => "true", "data-toggle" => "dropdown", :href => "#", :role => "button"}
            Account
            %span.caret
          %ul.dropdown-menu
            - unless current_user.incomplete_profile?
              %li
                %a{:href => edit_user_registration_path} Settings
            %li
              = link_to 'Log out', destroy_user_session_path, :method=>'delete'