config/routes.rb
Rails.application.routes.draw do
  constraints(Subdomain::Admin) do
    devise_for :admins, ActiveAdmin::Devise.config
    ActiveAdmin.routes(self)

    unauthenticated :admin do
      devise_scope :admin do
        root to: "active_admin/devise/sessions#new"
      end
    end

    authenticated :admin do
      root to: "admin/dashboard#index"
    end
  end

  devise_for :users, controllers: { sessions: "users/sessions" }

  constraints(Subdomain::Dashboard) do
    namespace :profiles do
      resources :build
    end

    resources :profiles, only: [:show, :update]

    namespace :requisitions do
      resources :sponsorships, except: [:index] do
        collection do
          get "list_schools"
          get "school/:school_id" => "sponsorships#school"
        end
      end
      resources :audits, except: [:index, :show, :destroy] do
        resources :reports
      end
      resources :offers, only: [:create, :destroy]
    end

    resources :reviews

    resources :invoices, only: [:index] do
      collection do
        put "pay_invoices"
      end
    end

    resources :requisitions, only: [:index, :show] do
      member do
        get "progress"
      end
      collection do
        get "search"
      end
    end


    resources :wallets, only: [:show, :create]

    resources :dashboard, only: [:index] do
      collection do
        put "upload_report" => "dashboard#upload_report", as: :upload_pdf_report
      end
    end
    root 'dashboard#index', as: :user_authenticated_root
  end


  root to: 'visitors#welcome'
end

app/controllers/requisitions/audits_controller.rb
class Requisitions::AuditsController < ApplicationController
  before_action :authorise_auditor, :authorise_student
  before_action :set_requisition, only: [:update]

  APPROVE = "Approve Offer"

  def update
    respond_to do |format|
      if params[:status].present?
        @audit_requisition.status = params[:status].to_i
        @audit_requisition.approved_at = DateTime.now if params[:status].to_i == Requisition::AUDIT_STATUS[:approved]
      end
      if @audit_requisition.update_attributes(audit_requisition_params)
        format.html { redirect_to(progress_requisition_path(@audit_requisition.sponsorship_requisition), :notice => Requisition::APPROVAL_STATE % { providership: "Auditing" }) }
        format.json { respond_with_bip(@audit_requisition) }
      else
        format.json { respond_with_bip(@audit_requisition) }
      end
    end
  end

  private

  def set_requisition
    begin
      @audit_requisition = current_sponsor.sponsorship_requisitions.find(params[:id]).audit_requisition
    rescue ActiveRecord::RecordNotFound
      redirect_to user_authenticated_root_url(subdomain: APP_SUBDOMAIN[:dashboard]), flash: { alert: "Requisition not found" }
    end
  end

  def audit_requisition_params
    params.require(:requisition).permit(:subject, :description, :provider_id, :provider_type)
  end
end

app/controllers/requisitions/offers_controller.rb
class Requisitions::OffersController < ApplicationController
  before_action do |controller|
    authorise_student
  end

  include OffersHelper

  def create
    @offer = current_participant.offers.build(requisition_id: params[:requisition_id])
    if @offer.save
      # NotificationsMailer.offer_placed(@offer.requisition.owner.user).deliver
      render json: { status: 200, requisition_id: params[:requisition_id], icon_html: sponsors_offers_list_icon_search(@offer).html_safe, offer_id: @offer.id, text: "Offer has been placed", url: requisitions_offer_path(@offer.id), method: :delete }
    else
      heading = content_tag(:ul, :class => 'list-unstyled') do
        @offer.errors[:alert_heading].collect do |item|
          content_tag(:li, item)
        end.join.html_safe
      end
      errors = content_tag(:ul) do
        @offer.errors[:info].collect do |item|
          content_tag(:li, item)
        end.join.html_safe
      end

      render json: { status: false, text: heading + errors }
    end
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy
    render json: { status: 200, requisition_id: @offer.requisition_id, offer_id: @offer.id, text: "Offer removed", url: requisitions_offers_path(requisition_id: @offer.requisition_id), method: :post }
  end
end

app/controllers/requisitions/reports_controller.rb
class Requisitions::ReportsController < ApplicationController
  before_action :authorise_student
  before_action :authorise_sponsor, except: [:show]
  before_action :set_requisition
  before_action :set_audit_items, only: [:new, :create, :edit, :update]
  before_action :set_report, only: [:edit, :update, :show]

  include AuditReportHelper

  def new
    begin
      @report = @requisition.build_audit_report
      @audit_items.each do |item|
        audit_finding = @report.audit_findings.build(audit_item_id: item.id)
        audit_finding.selected_container = AuditFinding::SELECTED_AUDIT_ITEM[:not_selected]
      end

      @audit_findings = @report.audit_findings
    rescue Exception
      redirect_to edit_requisitions_audit_report_path(@requisition, @requisition.audit_report), flash: { alert: "You have already created Audit Report. You can edit/download the report to complete the requisition process" }
    end
  end

  def create
    @report = @requisition.build_audit_report(report_params)
    if @report.save
      redirect_to edit_requisitions_audit_report_path(@requisition, @requisition.audit_report)
    else
      @audit_findings = @report.audit_findings
      render :new
    end
  end

  def edit
    unselected_items = @audit_items.where("name not in (?)", @report.audit_findings.map(&:audit_item).map(&:name))
    selected_items = @report.audit_findings
    selected_items.each do |item|
      item.selected_container = AuditFinding::SELECTED_AUDIT_ITEM[:selected]
    end
    unselected_items.each do |item|
      audit_finding = @report.audit_findings.build(audit_item_id: item.id)
      audit_finding.selected_container = AuditFinding::SELECTED_AUDIT_ITEM[:not_selected]
    end

    @audit_findings = @report.audit_findings.sort_by{|x| @audit_items.map(&:id).index x.audit_item_id}
  end

  def update
    if @report.update_attributes(report_params)
      redirect_to edit_requisitions_audit_report_path(@requisition, @requisition.audit_report)
    else
      @audit_findings = @report.audit_findings.sort_by{|x| @audit_items.map(&:id).index x.audit_item_id}
      render :edit
    end
  end

  def show
    @report.update_attribute(:updated_at, DateTime.now)
    respond_to do |format|
      format.html
      format.pdf do
        pdf  = render_to_string pdf: "EVS-Audit-Report",
               template: 'requisitions/reports/show.pdf.haml',
               layout: '/layouts/evs_audit_report.html.haml',
               print_media_type: true,
               title: "Requisition Audit Report - #{generated_report_format(@report.updated_at)}"
        send_data(pdf, filename: "EVS-Audit-Report-#{generated_report_format(@report.updated_at)}.pdf",  :type=>"application/pdf", :disposition => params[:deposition] || "attachment")
      end
    end
  end

  private

  def report_params
    params.require(:audit_report).permit(:good_controls, :weak_controls, :auditor_id, :audit_findings_attributes => [:id, :observation, :marks, :recommendation, :selected_container, :audit_item_id, :_destroy])
  end

  def set_requisition
    begin
      @requisition = current_participant.audit_requisitions.find(params[:audit_id])
    rescue ActiveRecord::RecordNotFound
      redirect_to user_authenticated_root_url(subdomain: APP_SUBDOMAIN[:dashboard]), flash: { alert: "Requisition not found" }
    end
  end

  def set_report
    @report = @requisition.audit_report
    if !@report
      redirect_to user_authenticated_root_url(subdomain: APP_SUBDOMAIN[:dashboard]), flash: { alert: "Requisition not found" }
    end
  end

  def set_audit_items
    @audit_items = AuditItem.all
  end
end

app/controllers/requisitions/sponsorships_controller.rb
class Requisitions::SponsorshipsController < ApplicationController
  before_action :authorise_sponsor, :authorise_auditor, :except => [:search]
  before_action :set_default_request_format, only: [:schools]
  before_action :authorise_sponsor, :authorise_auditor, only: [:destroy, :update]
  include CommonRequisition

  SAVE    = "Save Details"
  OPEN    = "Submit Requisition"
  APPROVE = "Approve Offer"

  @@selected_school = false

  def new
    @@selected_school = false
    @requisition = current_student.sponsorship_requisitions.build(student_id: current_student.id)
    set_geocode_location!(current_student.address, {click_able_marker: true})
  end

  def create
    @requisition = current_student.sponsorship_requisitions.build(new_requisition_params)
    set_geocode_location!(current_student.address, {click_able_marker: true})
    if @requisition.save
      redirect_to progress_requisition_path(@requisition), notice: "Requisitions has been saved."
    else
      flash[:alert] = "Review Errors"
      render :new
    end
  end

  def list_schools
    @schools = School.all

    if params[:school_selected].present? and params[:school_selected] == "true"
      @@selected_school = true
    else
      @@selected_school = false
    end

    data = @schools.as_json({:only => [:id, :name, :foundation_date], :include => :address, :selected_school => @@selected_school})

    render json: data
  end

  def school
    @school = School.find(params[:school_id])
    @@selected_school = true
    respond_to do |format|
      format.js
    end
  end

  def update
    status = Requisition::SPONSORSHIP_STATUS.fetch_key("draft")

    case params[:commit]
    when OPEN
      @requisition.publish_requisition
      status = Requisition::SPONSORSHIP_STATUS[:open]
      message = Requisition::PUBLIC_STATE % { providership: "Sponsorship" }
    when APPROVE
      @requisition.approved_at = DateTime.now
      status = Requisition::SPONSORSHIP_STATUS[:approved]
      message = Requisition::APPROVAL_STATE % { providership: "Sponsorship" }
    else
      message = Requisition::UPDATE_STATE
    end

    respond_to do |format|
      if @requisition.update_attributes(requisition_params(status))
        format.html { redirect_to(progress_requisition_path(@requisition), :notice => message) }
        format.json { respond_with_bip(@requisition) }
      else
        format.html { render template: "requisitions/progress/student" }
        format.json { respond_with_bip(@requisition) }
      end
    end
  end

  def destroy
    @requisition.destroy
    flash[:notice] = "Your requisition has been removed."
    redirect_to(user_authenticated_root_path)
  end

  private

    def new_requisition_params
      params.require(:requisition).permit(:subject, :description, :grade_level, :school_id, :start_date, :end_date)
    end

    def set_default_request_format
      request.format = :json unless params[:format]
    end

    def requisition_params(status)
      permitted_attributes = [
        :subject, :description, :grade_level, :school_id, :start_date, :end_date
      ]

      if params[:commit] == APPROVE
        permitted_attributes << :provider_type
        permitted_attributes << :provider_id
      end

      params.require(:requisition).permit(permitted_attributes).merge(status: status)
    end
end

app/controllers/requisitions_controller.rb
class RequisitionsController < ApplicationController
  before_action :authorise_student, :only => [:search, :show]
  before_action :set_requisition, only: [:show]
  include CommonRequisition

  def progress
    send("#{current_user.active_participant.pluralize}_progress")

    respond_to do |format|
      format.html { render template: "requisitions/progress/#{current_user.active_participant}" }
      format.js
    end
  end

  # Search Public Requisitions (Authorised for Sponsor && Auditor)
  def search
    @requisitions = Requisition.send(current_user.requisition_type).open_requisitions.search(params, current_user)

    if current_user.has_role?(Auditor)
      allow_popup(false)
      allow_popup(true) if current_auditor.has_on_going_case?
    end

    respond_to do |format|
      format.html
      format.json { render json: render_to_string(:partial => "requisitions/shared/search/results", :layout => false) }
    end
  end

  def show
    @sponsorship_requisition = @requisition
    @audit_requisition       = @sponsorship_requisition.audit_requisition

    addresses = [@requisition.student.address, @requisition.school.address]
    set_geocode_location!(addresses, zoom: 18) unless addresses.any?(&:nil?)
  end

  private

  # Public Open Requisitions
  def set_requisition
    begin
      @requisition = Requisition.open_requisitions.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to user_authenticated_root_url(subdomain: APP_SUBDOMAIN[:dashboard]), flash: { alert: "Requisition not found" }
    end
  end

  # Progress of Student's Case
  def students_progress
    @status = @requisition.status
    set_geocode_location!(@requisition.school.address, zoom: 18)

    if Requisition.unapproved_statuses.include? @status.to_sym
      # Since Statuses are not in Approved Category
      # Fetching only requisition for Sponsor
      case @status.to_sym
      when Requisition::SPONSORSHIP_STATUS.fetch_key(:open)
        @sponsorship_offers = @requisition.try(:sponsorship_offers)
      end
    else
      @audit_requisition = @requisition.audit_requisition  # Requisition for Auditor

      case @status.to_sym
      when Requisition::SPONSORSHIP_STATUS.fetch_key(:approved)
        @audit_offers = @audit_requisition.try(:audit_offers)
      when Requisition::SPONSORSHIP_STATUS.fetch_key(:validated)
        # Code Here
      end
    end
  end

  # Progress of Sponsor's Case
  def sponsors_progress
    @sponsorship_requisition = @requisition
    @audit_requisition       = @sponsorship_requisition.audit_requisition
    @audit_offers = @sponsorship_requisition.audit_requisition.audit_offers.includes(:creator)

    addresses = [@requisition.student.address, @requisition.school.address]
    set_geocode_location!(addresses) unless addresses.any?(&:nil?)
  end
end

app/helpers/requisitions_helper.rb
module RequisitionsHelper
  def short_description(desc)
    truncate(desc, length: 25, omission: '... (continued)')
  end

  def humanize_requisition_status(status)
    status.gsub("_", " ")
  end

  def requisition_progress_icons
    {
      "draft" => "edit-requisitions.png",
      "open" => "open-requisitions.png",
      "approved" => "approved-requisitions.png",
      "validated" => "audit-requisition-completed.png",
      "rejected" => "rejected-requisitions.png",
      "completed" => "completed-requisitions.png"
    }
  end

  def requisition_progress_classes
    {
      "draft" => "primary",
      "open" => "info",
      "approved" => "warning",
      "validated" => "success",
      "rejected" => "danger",
      "completed" => "success"
    }
  end

  def requisition_progress_status(status, requisition_status, participant)
    statuses =  if participant.is_a?(Student)
                  Requisition::SPONSORSHIP_STATUS
                else
                  Requisition::AUDIT_STATUS
                end
    if statuses[status.to_sym] < statuses[requisition_status.to_sym]
      %Q{<s>#{status.capitalize}</s>}
    elsif statuses[status.to_sym] == statuses[requisition_status.to_sym]
      %Q{<i class="fa fa-chevron-left"></i> #{status.capitalize}}
    else
      %Q{#{status.capitalize}}
    end
  end

  def published_format(publish_date)
    publish_date.strftime("%B %d, %Y") rescue nil
  end

  def invoice_status
    {
      "paid" => "success",
      "open" => "primary"
    }
  end
end

app/views/requisitions/reports/_form.html.haml
- content_for :javascript do
  AuditReport.initialize()
  AuditReport.progressReportSubmit();
.authform-container-fluid
  = validation_errors_notifications(@report)
.audit-form
  = simple_form_for @report, url: action, method: method do |f|
    = f.input :auditor_id, as: :hidden, input_html: { value: current_auditor.id }
    %blockquote.blockquote
      %h2 Select Audit Type
    %ul.list-inline.text-center#audit-items-list
      - @audit_items.each_with_index do |item, i|
        %li{data: { toggle: "tooltip", title: item.name }, class: @audit_findings[i].present? && @audit_findings[i].selected? ? "audit-item-selected" : ""}
          = link_to "#", data: { target: item.try(:name).parameterize.underscore + "_container" } do
            %i.fa.fa-3x{class: audit_items_icon[i]}
    #audit-items-fields
      = f.simple_fields_for :audit_findings, @audit_findings do |o|
        %div{ id: o.object.audit_item.try(:name).parameterize.underscore + "_container", class: o.object.not_selected? ? "hide-content" : "" }
          %blockquote.blockquote
            %i.fa{class: audit_items_icon[o.index]}
            = o.object.audit_item.try(:name)
          .authform-container-fluid
            = o.input :observation
            = o.input :recommendation, input_html: { rows: 6 }
            = o.input :marks, input_html: { maxlength: '2', size: '10', class: "report-marks-#{o.object.audit_item.try(:name).parameterize.underscore}" }, hint: 'Mention Marks out of 10'
            = o.input :audit_item_id, as: :hidden
            = o.input :selected_container, as: :hidden, input_html: { class: "selected-audit-item" }
            = o.input :_destroy, as: :hidden, input_html: { value: false, class: "destroy-audit-item" } if !o.object.new_record?
    %hr
    %blockquote.blockquote
      %h2 Any Further Suggestions
    .authform-container-fluid
      .row
        .col-md-6
          = f.input :good_controls
        .col-md-6
          = f.input :weak_controls


    .form-actions.text-right
      - if @report.new_record?
        = f.submit "Generate", class: "btn btn-primary btn-block-container"
      - else
        = f.submit "Save Report", class: "btn btn-primary btn-block-container"
        = link_to upload_pdf_report_dashboard_index_path(audit_report_id: @report, format: :json), id: "submitReport", class: "btn btn-warning btn-block-container" do
          %i.fa.fa-file-text
          Submit Report

app/views/requisitions/reports/edit.html.haml
%h1.text-center.page-header
  Edit Audit Report For Requisition
  %br
  = @requisition.subject
.audit-report
  .report-criteria
    .alert.alert-info
      %button.close.cancel{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
      %h4 Requisition Result Criteria
      %ul
        %li Every Audit Item will have Observation, Recommendation, Marks Distribution, e.g. Physical Interview is an audit item for which auditor has to fill all three fields and based on marks audit results will be calculated.
        %li Auditor can also provide Good and Weak Controls if there is any for the student.
        %li The marks of audit item which would sum up the report and results the Success or Failure of the requisition. In our system each marks per item will be out of 10.
        %li
          Following are the Audit Items which should be mainly considered
          %ol
            - @audit_items.each do |item|
              %li= item.name
  .report-status-label
    %table.table
      %tbody
        %tr
          %th.col-md-3
            Report Generated On
          %td
            %span.label.label-warning= generated_report_format(@report.created_at)
        %tr
          %th.col-md-2
            Total Marks
          %td
            %span.label.label-warning= number_with_decimal @report.total_marks
        %tr
          %th.col-md-2
            Result
          %td
            %span.label{class: result_label[@report.result]}= @report.result.humanize
    = link_to requisitions_audit_report_path(@requisition, @report, deposition: "inline", format: :pdf), class: "btn btn-info btn-block-container preview-report", target: "_blank" do
      %i.fa.fa-file-text
      Preview Report

  = render "form", action: requisitions_audit_report_path(@requisition, @report), method: :put

  .upload-report-form
    %p.file-name.hide-content
    %p#reportUploadError.text-danger.hide-content
    .list-group#report-files
    %script#reportUploadProgressTemplate{:type => "text/x-jquery-tmpl"}
      <div class="list-group-item">
      <div class="progress progress-striped active">
      <div class="progress-bar progress-bar-success" style="width: 0%;"></div>
      </div>
      </div>
    %script#reportUploadItemTemplate{:type => "text/x-jquery-tmpl"}
      <div class="list-group-item">
      <button type="button" class="close dismissable-parent">×</button>
      <span class="glyphicon glyphicon-file"></span> Report has successfully submitted.
      </div>

app/views/requisitions/reports/new.html.haml
%h1.text-center.page-header
  Generate Audit Report
.audit-report
  .authform-container-fluid.report-criteria
    .alert.alert-info
      %button.close.cancel{"aria-label" => "Close", "data-dismiss" => "alert", :type => "button"}
        %span{"aria-hidden" => "true"} ×
      %h4 Requisition Result Criteria
      %ul
        %li Every Audit Item will have Observation, Recommendation, Marks Distribution, e.g. Physical Interview is an audit item for which auditor has to fill all three fields and based on marks audit results will be calculated.
        %li Auditor can also provide Good and Weak Controls if there is any for the student.
        %li The marks of audit item which would sum up the report and results the Success or Failure of the requisition. In our system each marks per item will be out of 10.
        %li
          Following are the Audit Items which should be mainly considered
          %ol
            - @audit_items.each do |item|
              %li= item.name
  = render "form", action: requisitions_audit_reports_path(@requisition), method: :post

app/views/requisitions/reports/show.html.haml
.header
  = image_tag "evs_logo.png", class: "img-responsive"
  .pull-right
    %label Date
    = Date.today
.main
  %blockquote.blockquote
    %h3
      Audit Report For Requisition
      %small= @requisition.subject

  %h3.text-center
    Overall Summary

  %table.table.table-bordered#overall_summary
    %tbody
      %tr
        %th.text-center
          Total Marks
        %th.text-center
          Out Of
        %th.text-center
          Percentage (%)
        %th.text-center
          Result
      %tr
        %td
          = number_with_decimal @report.total_marks
        %td
          = @report.total_report_marks
        %td
          = number_to_percentage @report.percentage
        %td
          = @report.result.humanize

  %h3.text-center
    Control Summary

  %table.table.table-bordered#control_summary
    %thead
      %tr
        %th.text-center.good_controls
          Good Controls
        %th.text-center.weak_controls
          Weak Controls
    %tbody
      %tr
        %td
          = simple_format(@report.good_controls)
        %td
          = simple_format(@report.weak_controls)

  %h3.text-center
    Detailed Observation And Recommendation
  .observation_summary
    - @report.audit_findings.each_with_index do |finding, i|
      %table.table.table-bordered
        %tbody
          %tr
            %th.heading{colspan: 2}
              Observation #
              = i += 1
          %tr
            %td{colspan: 2}
              = finding.observation
          %tr
            %th.heading{colspan: 2}
              Recommendation
          %tr
            %td{colspan: 2}
              = finding.recommendation
          %tr
            %th.heading{colspan: 2}
              Marks
          %tr
            %td.text-center
              %label Obtained:
              = number_with_decimal finding.marks
            %td.text-center
              %label Out Of:
              = AuditReport::TOTAL_REPORT_MARKS


.footer
  Education Voucher Scheme

app/views/requisitions/reports/show.pdf.haml
%h3
  Auditor
.row
  .col-md-6
    %label Auditor:
    = @report.auditor.try(:user).full_name
    %br
    %label Email:
    = @report.auditor.try(:user).email
    %br
    %label Phone Number:
    +92316-2683386
%blockquote.blockquote
  %h3
    Audit Report For Requisition
    %small= @requisition.subject

%h3.text-center
  Overall Summary

%table.table.table-bordered#overall_summary
  %tbody
    %tr
      %th.text-center
        Total Marks
      %th.text-center
        Out Of
      %th.text-center
        Percentage (%)
      %th.text-center
        Result
    %tr
      %td
        = number_with_decimal @report.total_marks
      %td
        = @report.total_report_marks
      %td
        = number_to_percentage @report.percentage
      %td
        = @report.result.humanize

%h3.text-center
  Control Summary

%table.table.table-bordered#control_summary
  %thead
    %tr
      %th.text-center.good_controls
        Good Controls
      %th.text-center.weak_controls
        Weak Controls
  %tbody
    %tr
      %td
        = simple_format(@report.good_controls)
      %td
        = simple_format(@report.weak_controls)

%h3.text-center.detailed_observation_section
  Detailed Observation And Recommendation
.observation_summary
  - @report.audit_findings.each_with_index do |finding, i|
    %table.table.table-bordered
      %tbody
        %tr
          %th.heading{colspan: 2}
            Observation #
            = i += 1
        %tr
          %td{colspan: 2}
            = finding.observation
        %tr
          %th.heading{colspan: 2}
            Recommendation
        %tr
          %td{colspan: 2}
            = finding.recommendation
        %tr
          %th.heading{colspan: 2}
            Marks
        %tr
          %td.text-center
            %label Obtained:
            = number_with_decimal finding.marks
          %td.text-center
            %label Out Of:
            = AuditReport::TOTAL_REPORT_MARKS